# Generated by Django 4.2.6 on 2023-12-16 11:51

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("common_users", "0002_alter_commonuser_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "db_table": "faqs",
            },
        ),
        migrations.AddField(
            model_name="commonuser",
            name="telegram_user_id",
            field=models.CharField(
                default="",
                max_length=100,
                unique=True,
                verbose_name="Telegram user id",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="commonuser",
            name="username",
            field=models.CharField(default="", verbose_name="Username"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commonuser",
            name="chat_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Chat id"
            ),
        ),
        migrations.AlterField(
            model_name="commonuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="commonuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Phone"
            ),
        ),
    ]
