# Generated by Django 4.2.6 on 2023-12-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common_users",
            "0003_faq_commonuser_telegram_user_id_commonuser_username_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commonuser",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="commonuser",
            name="email",
        ),
        migrations.AddField(
            model_name="commonuser",
            name="car_number",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Car number"
            ),
        ),
        migrations.AddField(
            model_name="commonuser",
            name="car_number_region",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Car number region"
            ),
        ),
        migrations.AddField(
            model_name="commonuser",
            name="car_serial_number",
            field=models.CharField(
                blank=True,
                max_length=3,
                null=True,
                verbose_name="Car serial number",
            ),
        ),
        migrations.AlterField(
            model_name="commonuser",
            name="username",
            field=models.CharField(unique=True, verbose_name="Username"),
        ),
    ]
