# Generated by Django 4.2.6 on 2023-12-17 23:44

import core.models.model_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_product_expiration_time_product_lessor_and_more"),
        (
            "common_users",
            "0004_remove_commonuser_birthday_remove_commonuser_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Phone",
            ),
        ),
        migrations.CreateModel(
            name="CommonUserPurchase",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "amount",
                    core.models.model_fields.AmountField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="orders.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "CommonUser purchase",
                "verbose_name_plural": "CommonUser purchases",
                "db_table": "common_user_purchases",
            },
        ),
    ]
