# Generated by Django 4.2.6 on 2023-12-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_users", "0005_alter_commonuser_phone_commonuserpurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonuserpurchase",
            name="is_completed",
            field=models.BooleanField(
                default=False, verbose_name="Is completed"
            ),
        ),
    ]
