# Generated by Django 4.2.6 on 2023-10-10 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatSetting',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('bot_token', models.CharField(max_length=20, verbose_name='Bot token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Chat Setting',
                'verbose_name_plural': 'User Chat Settings',
                'db_table': 'user_chat_settings',
            },
        ),
        migrations.CreateModel(
            name='UseChatHistory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(verbose_name='Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Chat History',
                'verbose_name_plural': 'User Chat Histories',
                'db_table': 'user_chat_histories',
            },
        ),
    ]
