# Generated by Django 4.2.6 on 2023-10-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatsetting',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chat Id'),
        ),
        migrations.AlterField(
            model_name='usechathistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userchatsetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
