# Generated by Django 4.2.6 on 2023-12-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_free",
            field=models.BooleanField(default=True, verbose_name="Is free"),
        ),
    ]
