# Generated by Django 4.2.6 on 2023-12-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_product_expiration_time_product_lessor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="expiration_time",
        ),
        migrations.AddField(
            model_name="product",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_took_place",
            field=models.BooleanField(
                default=False, verbose_name="Is took place"
            ),
        ),
    ]
